const knowledgeBase = {
  "Galaxy Buds2 Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wear detection",
      "Wireless charging",
    ],
    price: 180,
    shape: "Bud",
  },
  "OPPO Enco X2": {
    features: [
      "24-bit",
      "Active noise cancelling",
      "Fast pair",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 170,
    shape: "Stem",
  },
  "Soundcore Liberty Air 2 Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 60,
    shape: "Stem",
  },
  "LG TONE Free T90": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Dolby head tracking",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 230,
    shape: "Stem",
  },
  "Bowers & Wilkins PI7": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Audio retransmission",
      "In-ear detection",
    ],
    price: 350,
    shape: "Bud",
  },
  "Skullcandy Indy ANC": {
    features: [
      "Active noise cancelling",
      "Tile tracking",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 50,
    shape: "Stem",
  },
  "NuraTrue Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "Spatial audio",
    ],
    price: 330,
    shape: "Bud",
  },
  "Soundcore Liberty 3 Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 100,
    shape: "Bud",
  },
  "TOZO Crystal Buds": {
    features: [
      "Battery percentage meter",
      "In-app eq",
      "Mono mode",
      "Wireless charging",
    ],
    price: 40,
    shape: "Bud",
  },
  "Marshall Motif ANC": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
      "Wireless charging",
      "In-ear detection",
    ],
    price: 200,
    shape: "Stem",
  },
  "1MORE True Wireless Active Noise Cancelling In-Ear Headphones": {
    features: [
      "Active noise cancelling",
      "Thx certified",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 100,
    shape: "Bud",
  },
  "OnePlus Buds Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Transparency mode",
      "Warp charge",
      "Wireless charging",
    ],
    price: 100,
    shape: "Stem",
  },
  "JBL Reflect Flow Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 180,
    shape: "Bud",
  },
  "Jaybird Vista 2": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mil-std-810g",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 100,
    shape: "Bud",
  },
  "Montblanc MTB 03": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wear detection",
    ],
    price: 405,
    shape: "Bud",
  },
  Fairbuds: {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "User-replaceable batteries",
      "In-ear detection",
    ],
    price: 162,
    shape: "Bud",
  },
  "Soundcore Life P3": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 75,
    shape: "Stem",
  },
  "Belkin Soundform Immerse": {
    features: [
      "Active noise cancelling",
      "Apple find my",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 145,
    shape: "Bud",
  },
  "Skullcandy Sesh ANC": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Tile tracking",
      "Transparency mode",
    ],
    price: 100,
    shape: "Bud",
  },
  "Redmi Buds 3 Pro": {
    features: [
      "Active noise cancelling",
      "In-ear detection",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 60,
    shape: "Bud",
  },
  "Huawei Freebuds Pro": {
    features: [
      "Active noise cancelling",
      "Find my earbuds",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 120,
    shape: "Stem",
  },
  "MOMENTUM True Wireless 3": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 200,
    shape: "Bud",
  },
  "Galaxy Buds+": {
    features: [
      "In-app eq",
      "Mono mode",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 120,
    shape: "Bud",
  },
  "Lypertek PurePlay Z3 2.0": {
    features: [
      "Find my earbuds",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 99,
    shape: "Bud",
  },
  "Technics EAH-AZ40": {
    features: [
      "Find my earbuds",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
    ],
    price: 150,
    shape: "Bud",
  },
  "JBL Wave Beam": {
    features: [
      "Google fast pair",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
    ],
    price: 61,
    shape: "Stem",
  },
  "JBL Wave Buds": {
    features: [
      "Battery level indicator",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
    ],
    price: 48,
    shape: "Bud",
  },
  "Yamaha TW-ES5A Sports Earbuds": {
    features: [
      "In-app eq",
      "In-ear detection",
      "Transparency mode",
      "Low-latency mode",
    ],
    price: 150,
    shape: "Stem",
  },
  "Sony WF-C700N": {
    features: [
      "Active noise cancelling",
      "Dsee",
      "Google fast pair",
      "In-app eq",
      "Microsoft swift pair",
      "Multipoint",
      "Transparency mode",
    ],
    price: 120,
    shape: "Bud",
  },
  "Soundcore Life P3i": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
    ],
    price: 50,
    shape: "Stem",
  },
  "Powerbeats Pro": {
    features: [
      "Dolby atmos",
      "In-app eq",
      "Transparency mode",
      "Wear detection (auto play/pause)",
    ],
    price: 200,
    shape: "Hook",
  },
  "Xiaomi Buds 4 Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Spatial audio",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 139,
    shape: "Stem",
  },
  "1MORE ColorBuds 2": {
    features: [
      "Active noise cancelling",
      "In-ear detection",
      "Mono mode",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 60,
    shape: "Bud",
  },
  "Status Between 3ANC": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mono mode",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 200,
    shape: "Stem",
  },
  "Technics EAH-AZ60": {
    features: [
      "Active noise cancelling",
      "Find my earbuds",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
    ],
    price: 230,
    shape: "Bud",
  },
  "Audio Technica ATH-TWX7": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
    ],
    price: 199,
    shape: "Stem",
  },
  "1MORE PistonBuds Pro": {
    features: [
      "Active noise cancelling",
      "Mono mode",
      "Transparency mode",
      "Wear detection",
    ],
    price: 60,
    shape: "Bud",
  },
  "Fairphone True Wireless Stereo Earbuds": {
    features: [
      "Active noise cancelling",
      "In-ear detection",
      "Transparency mode",
      "Mono mode",
    ],
    price: 109,
    shape: "Stem",
  },
  "EarFun Air Pro SV": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 90,
    shape: "Stem",
  },
  "OnePlus Nord Buds 2": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "In-app eq",
      "Transparency mode",
    ],
    price: 59,
    shape: "Stem",
  },
  "vivo TWS 3e": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Spatial audio",
      "Transparency mode",
    ],
    price: 25,
    shape: "Stem",
  },
  "JLab Epic Lab Edition": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Google fast pair",
      "In-app eq",
      "Multipoint",
      "Spatial audio",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 200,
    shape: "Bud",
  },
  "OnePlus Buds Pro 2 Lite": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "Spatial audio",
      "Transparency mode",
    ],
    price: 115,
    shape: "Stem",
  },
  "JBL Quantum TWS": {
    features: [
      "2.4 ghz adapter",
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Simultaneous bluetooth/2.4ghz connection",
    ],
    price: 130,
    shape: "Stem",
  },
  "1MORE Evo": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 150,
    shape: "Bud",
  },
  "EarFun Air Pro 3": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Ultra low latency mode",
      "Wireless charging",
    ],
    price: 56,
    shape: "Stem",
  },
  "JBL Live Pro 2": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 100,
    shape: "Stem",
  },
  "Philips Fidelio T1": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 109,
    shape: "Bud",
  },
  "LG TONE Free T60": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Germicidal uv",
    ],
    price: 150,
    shape: "Stem",
  },
  "Jabra Elite 7 Active": {
    features: [
      "Active noise cancelling",
      "Alexa built-in",
      "Mono mode",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 180,
    shape: "Bud",
  },
  "Philips T8506": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 100,
    shape: "Bud",
  },
  "Jabra Elite 5": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Microsoft swift pair",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 150,
    shape: "Bud",
  },
  "Huawei FreeBuds 5i": {
    features: [
      "Active noise cancelling",
      "Find my earbuds",
      "In-ear detection",
      "Low-latency mode",
      "Multipoint",
      "Transparency mode",
    ],
    price: 108,
    shape: "Stem",
  },
  "Jabra Elite 4": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Microsoft swift pair",
      "Multipoint",
      "Transparency mode",
      "Mono mode",
    ],
    price: 100,
    shape: "Bud",
  },
  "Huawei FreeBuds Pro 3": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "In-ear detection",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 200,
    shape: "Stem",
  },
  "PistonBuds Pro Q30": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "In-ear detection",
    ],
    price: 50,
    shape: "Stem",
  },
  "Nothing Ear (2)": {
    features: [
      "Active noise cancelling",
      "Find my earbuds",
      "Google fast pair",
      "In-app eq",
      "In-ear detection",
      "Microsoft swift pair",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 149,
    shape: "Stem",
  },
  "Jabra Elite 10": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Fast pair",
      "In-ear detection",
      "Multipoint",
      "Swift pair",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 250,
    shape: "Bud",
  },
  "Jabra Elite 8 Active": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Fast pair",
      "In-app eq",
      "In-ear detection",
      "Mil-std-810h",
      "Multipoint",
      "Swift pair",
      "Transparency mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "Jabra Elite 3": {
    features: ["Alexa built-in", "In-app eq", "Transparency mode", "Mono mode"],
    price: 80,
    shape: "Bud",
  },
  "Jabra Elite 85t": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 230,
    shape: "Bud",
  },
  "Klipsch T5 II True Wireless ANC": {
    features: [
      "Active noise cancelling",
      "Dirac hd",
      "In-app eq",
      "Metal case",
      "Transparency mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "Sony WF-1000XM3": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "In-app eq",
      "Transparency mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "1MORE ComfoBuds Pro": {
    features: [
      "Active noise cancelling",
      "Auto play-pause",
      "In-app eq",
      "Transparency mode",
    ],
    price: 55,
    shape: "Stem",
  },
  "JLab Air Sport 3rd gen": {
    features: [
      "Google fast pair",
      "In-app eq",
      "Mono mode",
      "Multipoint",
      "Tile tracking",
      "Transparency mode",
    ],
    price: 70,
    shape: "Hook",
  },
  "JLab JBuds Air Pro": {
    features: [
      "In-app eq",
      "Mono mode",
      "Multipoint",
      "Tile tracking",
      "Transparency mode",
    ],
    price: 60,
    shape: "Bud",
  },
  "JLab Epic Air Sport ANC 2nd gen": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Low-latency mode",
      "Tile tracking",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 80,
    shape: "Hook",
  },
  "Sony WF-1000XM4": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 280,
    shape: "Bud",
  },
  "LG TONE Free FP8": {
    features: [
      "Active noise cancelling",
      "Fast pair",
      "In-app eq",
      "Swift pair",
      "Transparency mode",
      "Uv disinfecting case",
      "Wireless charging",
    ],
    price: 180,
    shape: "Stem",
  },
  "Beyerdynamic Free Byrd": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 230,
    shape: "Bud",
  },
  "FIIL CC Pro2": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Sleep mode",
      "Transparency mode",
      "Wear detection",
    ],
    price: 100,
    shape: "Stem",
  },
  "Surface Earbuds": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "Soundcore Life A3i": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Mono mode",
      "Transparency mode",
    ],
    price: 60,
    shape: "Bud",
  },
  "Bose QuietComfort Ultra Earbuds": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Google fast pair",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 300,
    shape: "Stem",
  },
  "Soundcore Liberty 4 NC": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 100,
    shape: "Stem",
  },
  "realme Buds Air 5 Pro": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "Transparency mode",
      "Spatial audio",
    ],
    price: 60,
    shape: "Stem",
  },
  "AirPods Pro (2nd generation, Lightning)": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Ear detection",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 250,
    shape: "Stem",
  },
  "AirPods Pro (2nd generation, USB-C)": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "Ear detection",
      "In-app eq",
      "Lossless audio with vision pro",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 250,
    shape: "Stem",
  },
  "Denon PerL Pro": {
    features: [
      "Active noise cancelling",
      "Dirac virtuo",
      "Dolby atmos",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wear detection",
    ],
    price: 349,
    shape: "Bud",
  },
  "Razer Hammerhead Hyperspeed": {
    features: [
      "2.4 ghz adapter",
      "Active noise cancelling",
      "Chroma rgb",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
      "Simultaneous usb/bluetooth connection",
    ],
    price: 150,
    shape: "Stem",
  },
  "Philips Fidelio T2": {
    features: [
      "Active noise cancelling",
      "Auracast",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 279,
    shape: "Bud",
  },
  "Sennheiser Momentum True Wireless 4": {
    features: [
      "Active noise cancelling",
      "Auracast",
      "In-app eq",
      "Le audio",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 300,
    shape: "Bud",
  },
  "Beats Studio Buds +": {
    features: [
      "Active noise cancelling",
      "Apple find my",
      "Dolby atmos",
      "Google fast pair",
      "Multipoint",
      "Transparency mode",
    ],
    price: 170,
    shape: "Bud",
  },
  "Soundcore Liberty 4": {
    features: [
      "Active noise cancelling",
      "Heart rate monitor",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 150,
    shape: "Stem",
  },
  "OnePlus Buds Pro 2": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 130,
    shape: "Stem",
  },
  "Creative Outlier Air V3": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
      "Mono mode",
    ],
    price: 42,
    shape: "Bud",
  },
  "FIIL CC Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 53,
    shape: "Stem",
  },
  "Galaxy Buds2": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 90,
    shape: "Bud",
  },
  "Bowers & Wilkins Pi7 S2": {
    features: [
      "Active noise cancelling",
      "Audio retransmission",
      "Transparency mode",
      "Wireless charging",
      "Wear detection",
    ],
    price: 400,
    shape: "Bud",
  },
  "1MORE Aero": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Spatial audio",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 110,
    shape: "Stem",
  },
  "Nothing Ear (1)": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "In-ear detection",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 100,
    shape: "Stem",
  },
  "Beoplay EX": {
    features: [
      "Active noise cancelling",
      "Google fast pair",
      "In-app eq",
      "Microsoft swift pair",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 400,
    shape: "Stem",
  },
  "Xiaomi Buds 3T Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Spatial audio",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 150,
    shape: "Stem",
  },
  "Master & Dynamic MW08 Sport": {
    features: [
      "Active noise cancelling",
      "Ipx4 case",
      "Multipoint",
      "Transparency mode",
      "Usb-a bluetooth adapter",
      "Wireless charging",
    ],
    price: 349,
    shape: "Bud",
  },
  "Xiaomi Buds 3": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 93,
    shape: "Stem",
  },
  "Xiaomi Buds 3 Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 93,
    shape: "Stem",
  },
  "Belkin SoundForm Flow": {
    features: [
      "Active noise cancelling",
      "Mono mode",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 90,
    shape: "Stem",
  },
  "EarFun Air S": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 70,
    shape: "Stem",
  },
  "Echo Buds (2nd Gen)": {
    features: [
      "Active noise cancelling",
      "Alexa built-in",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 100,
    shape: "Bud",
  },
  "Beoplay EQ": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "In-ear detection",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 300,
    shape: "Bud",
  },
  "Redmi Buds 4 Pro": {
    features: [
      "Active noise cancelling",
      "In-ear detection",
      "Multipoint",
      "Transparency mode",
    ],
    price: 100,
    shape: "Stem",
  },
  "EarFun Air Pro": {
    features: [
      "Active noise cancelling",
      "Mono mode",
      "Transparency mode",
      "In-ear detection",
    ],
    price: 80,
    shape: "Stem",
  },
  "Redmi Buds 4": {
    features: [
      "Active noise cancelling",
      "Low-latency mode",
      "Transparency mode",
      "In-ear detection",
    ],
    price: 29,
    shape: "Bud",
  },
  "Logitech Zone True Wireless": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Usb-a bluetooth receiver",
      "Wireless charging",
    ],
    price: 300,
    shape: "Bud",
  },
  "Soundcore Space A40": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 100,
    shape: "Bud",
  },
  "Lypertek PurePlay Z5": {
    features: [
      "Active noise cancelling",
      "Find my earbuds",
      "In-app eq",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 99,
    shape: "Stem",
  },
  "Sony LinkBuds S": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "Audio-Technica ATH-TWX9": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
    ],
    price: 300,
    shape: "Stem",
  },
  "Galaxy Buds Pro": {
    features: [
      "Active noise cancelling",
      "Automatic transparency",
      "Dolby atmos",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 180,
    shape: "Bud",
  },
  "Beats Fit Pro": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "In-ear detection",
      "Transparency mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "OnePlus Buds Z2": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "In-app eq",
      "Mono mode (via app)",
      "Transparency mode",
    ],
    price: 80,
    shape: "Stem",
  },
  "Jabra Elite 7 Pro": {
    features: [
      "Active noise cancelling",
      "Alexa built-in",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 200,
    shape: "Bud",
  },
  "vivo TWS 3 Pro": {
    features: [
      "Active noise cancelling",
      "Body temperature sensor",
      "Multipoint",
      "Transparency mode",
    ],
    price: 140,
    shape: "Stem",
  },
  "JLab Epic Air Sport ANC": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Tile tracking",
      "Transparency mode",
      "Wear detection",
      "Wireless charging",
    ],
    price: 80,
    shape: "Hook",
  },
  "Razer Hammerhead True Wireless Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Low-latency mode",
      "Thx certified",
      "Transparency mode",
    ],
    price: 100,
    shape: "Stem",
  },
  "Beats Studio Buds": {
    features: [
      "Active noise cancelling",
      "Dolby atmos",
      "In-app eq",
      "Transparency mode",
    ],
    price: 100,
    shape: "Bud",
  },
  "Razer Hammerhead True Wireless (2021)": {
    features: [
      "Active noise cancelling",
      "Chroma rgb",
      "In-app eq",
      "Transparency mode",
    ],
    price: 90,
    shape: "Stem",
  },
  "Pixel Buds Pro": {
    features: [
      "Active noise cancelling",
      "In-app eq",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 200,
    shape: "Bud",
  },
  "AirPods (3rd generation)": {
    features: [
      "In-app eq",
      "Magsafe",
      "Spatial audio",
      "Wireless charging",
      "Wear detection",
    ],
    price: 180,
    shape: "Stem",
  },
  "vivo TWS Air Pro": {
    features: [
      "3d audio",
      "Active noise cancelling",
      "Spatial audio",
      "Transparency mode",
    ],
    price: 42,
    shape: "Stem",
  },
};

export default knowledgeBase;

// import fs from "fs";

// for (const [key, value] of Object.entries(knowledgeBase)) {
//   if (value.features.length < 4) {
//     delete knowledgeBase[key];
//   }
//   //Sort features alphabetically
//   value.features.sort();
//   //Features to lowercase but first letter uppercase
//   value.features = value.features.map(
//     (feature) =>
//       feature.charAt(0).toUpperCase() + feature.slice(1).toLowerCase()
//   );
// }

// fs.writeFile("earbuds.json", JSON.stringify(knowledgeBase, null, 2), (err) => {
//   if (err) throw err;
//   console.log("Data written to file");
// });

let featuresSet = new Set();

for (const [key, value] of Object.entries(knowledgeBase)) {
  let features = value.features;
  features.forEach((feature) => featuresSet.add(feature));
}

console.log(featuresSet);
