const knowledgeBase = {
  "Baseus Encok W06": {
    features: ["Wireless charging", "Wear detection. mono mode"],
    price: 68,
    shape: "Stem",
  },
  "Galaxy Buds2 Pro": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
      "Active noise cancelling",
      "Wear detection",
    ],
    price: 180,
    shape: "Bud",
  },
  "OPPO Enco X2": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
      "Active noise cancelling",
      "Multipoint",
      "Fast Pair",
      "24-bit",
    ],
    price: 170,
    shape: "Stem",
  },
  "Soundcore Liberty Air 2 Pro": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
      "Active noise cancelling",
    ],
    price: 60,
    shape: "Stem",
  },
  "Beoplay E8 3rd gen": {
    features: ["Wireless charging", "Transparency mode", "In-app EQ"],
    price: 250,
    shape: "Bud",
  },
  "LG TONE Free T90": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "Active noise cancelling",
      "In-app EQ",
      "Multipoint",
      "Dolby Atmos",
      "Dolby Head Tracking",
    ],
    price: 230,
    shape: "Stem",
  },
  "Bowers & Wilkins PI7": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "Active noise cancelling",
      "audio retransmission",
      "in-ear detection",
    ],
    price: 350,
    shape: "Bud",
  },
  "Bowers & Wilkins Pi5 S2": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "Active noise cancelling",
    ],
    price: 300,
    shape: "Bud",
  },
  "Earfun Free Pro": {
    features: [
      "Wireless charging",
      "Transparency mode",
      "Active noise cancelling",
    ],
    price: 50,
    shape: "Bud",
  },
  "Skullcandy Indy ANC": {
    features: [
      "Wireless charging",
      "Tile tracking",
      "Transparency mode",
      "Active noise cancelling",
    ],
    price: 50,
    shape: "Stem",
  },
  "Skullcandy Grind Fuel": {
    features: ["Wireless charging", "Tile tracking", "Transparency mode"],
    price: 100,
    shape: "Bud",
  },
  "NuraTrue Pro": {
    features: [
      "Wireless charging",
      "Multipoint",
      "Transparency mode",
      "Active noise cancelling",
      "spatial Audio",
    ],
    price: 330,
    shape: "Bud",
  },
  "Soundcore Liberty 3 Pro": {
    features: [
      "Wireless charging",
      "Multipoint",
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
    ],
    price: 100,
    shape: "Bud",
  },
  "SOUNDPEATS Q": {
    features: ["Wireless charging", "Mono mode"],
    price: 50,
    shape: "Stem",
  },
  "Mpow M12": {
    features: ["Wireless charging", "Mono mode"],
    price: 25,
    shape: "Bud",
  },
  "Soundcore Life A1": {
    features: ["Wireless charging", "Mono mode"],
    price: 50,
    shape: "Bud",
  },
  "EarFun Air (2022)": {
    features: ["Wireless charging", "In-ear detection"],
    price: 60,
    shape: "Stem",
  },
  "TOZO Crystal Buds": {
    features: [
      "Wireless charging",
      "In-app EQ",
      "Battery percentage meter",
      "Mono mode",
    ],
    price: 40,
    shape: "Bud",
  },
  "Marshall Motif ANC": {
    features: [
      "Wireless charging",
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Mono mode",
      "in-ear detection",
    ],
    price: 200,
    shape: "Stem",
  },
  "Moondrop Alice": {
    features: ["Wireless charging", "In-app EQ"],
    price: 190,
    shape: "Bud",
  },
  "Soundcore Liberty 2 Pro": {
    features: ["Wireless charging", "In-app EQ"],
    price: 50,
    shape: "Bud",
  },
  "1MORE True Wireless Active Noise Cancelling In-Ear Headphones": {
    features: [
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
      "THX Certified",
      "wear detection",
    ],
    price: 100,
    shape: "Bud",
  },
  "OnePlus Buds Pro": {
    features: [
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
      "Multipoint",
      "Warp charge",
    ],
    price: 100,
    shape: "Stem",
  },
  "JBL Reflect Flow Pro": {
    features: [
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Mono mode",
    ],
    price: 180,
    shape: "Bud",
  },
  "Jaybird Vista 2": {
    features: [
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "MIL-STD-810G",
    ],
    price: 100,
    shape: "Bud",
  },
  "Bowers & Wilkins PI5": {
    features: [
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
    ],
    price: 150,
    shape: "Bud",
  },
  "Montblanc MTB 03": {
    features: [
      "Wear detection",
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
    ],
    price: 405,
    shape: "Bud",
  },
  Fairbuds: {
    features: [
      "User-replaceable batteries",
      "in-ear detection",
      "Multipoint",
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
    ],
    price: 162,
    shape: "Bud",
  },
  "Soundcore Life P3": {
    features: [
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Active noise cancelling",
    ],
    price: 75,
    shape: "Stem",
  },
  "Belkin Soundform Immerse": {
    features: [
      "Transparency mode",
      "Wireless charging",
      "Active noise cancelling",
      "Multipoint",
      "In-app EQ",
      "Apple Find My",
    ],
    price: 145,
    shape: "Bud",
  },
  "TOZO NC9 (2022)": {
    features: [
      "Transparency mode",
      "Wireless charging",
      "Active noise cancelling",
    ],
    price: 40,
    shape: "Bud",
  },
  "Skullcandy Indy Evo": {
    features: ["Transparency mode", "Tile tracking", "Mono mode"],
    price: 40,
    shape: "Stem",
  },
  "Skullcandy Sesh ANC": {
    features: [
      "Transparency mode",
      "Tile tracking",
      "In-app EQ",
      "Active noise cancelling",
    ],
    price: 100,
    shape: "Bud",
  },
  "Redmi Buds 3 Pro": {
    features: [
      "Transparency mode",
      "Multipoint",
      "Active noise cancelling",
      "Wireless charging",
      "In-ear detection",
    ],
    price: 60,
    shape: "Bud",
  },
  "Huawei Freebuds Pro": {
    features: [
      "Transparency mode",
      "Multipoint",
      "Active noise cancelling",
      "Wireless charging",
      "Find my earbuds",
    ],
    price: 120,
    shape: "Stem",
  },
  "Jabra Elite 75t": {
    features: ["Transparency mode", "Multipoint", "Active noise cancelling"],
    price: 95,
    shape: "Bud",
  },
  "Audio-Technica ATH-SQ1TW": {
    features: ["Transparency mode", "Multipoint"],
    price: 80,
    shape: "Bud",
  },
  "MOMENTUM True Wireless 3": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Multipoint",
      "Active noise cancelling",
    ],
    price: 200,
    shape: "Bud",
  },
  "Galaxy Buds+": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Mono mode",
    ],
    price: 120,
    shape: "Bud",
  },
  "Lypertek PurePlay Z3 2.0": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Find my earbuds",
    ],
    price: 99,
    shape: "Bud",
  },
  "Beoplay E8 Sport": {
    features: ["Transparency mode", "In-app EQ", "Wireless charging"],
    price: 200,
    shape: "Bud",
  },
  "Technics EAH-AZ40": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Multipoint",
      "Find my earbuds",
    ],
    price: 150,
    shape: "Bud",
  },
  "JBL Wave Beam": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Mono mode",
      "Google Fast Pair",
    ],
    price: 61,
    shape: "Stem",
  },
  "JBL Wave Buds": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Mono mode",
      "Battery level indicator",
    ],
    price: 48,
    shape: "Bud",
  },
  "Yamaha TW-ES5A Sports Earbuds": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "In-ear detection",
      "low-latency mode",
    ],
    price: 150,
    shape: "Stem",
  },
  "Cambridge Audio Melomania Touch": {
    features: ["Transparency mode", "In-app EQ", "Find my earbuds"],
    price: 100,
    shape: "Bud",
  },
  "Sony WF-C700N": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Active noise cancelling",
      "Multipoint",
      "DSEE",
      "Microsoft Swift Pair",
      "Google Fast Pair",
    ],
    price: 120,
    shape: "Bud",
  },
  "Soundcore Life P3i": {
    features: [
      "Transparency mode",
      "In-app EQ",
      "Active noise cancelling",
      "Mono mode",
    ],
    price: 50,
    shape: "Stem",
  },
  "Final ZE8000": {
    features: ["Transparency mode", "In-app EQ", "Active noise cancelling"],
    price: 350,
    shape: "Stem",
  },
  "Sennheiser CX Plus True Wireless": {
    features: ["Transparency mode", "In-app EQ", "Active noise cancelling"],
    price: 130,
    shape: "Bud",
  },
  "Soundcore Life A2 NC": {
    features: ["Transparency mode", "In-app EQ", "Active noise cancelling"],
    price: 55,
    shape: "Bud",
  },
  "JBL Endurance Race TWS": {
    features: ["Transparency mode", "In-app EQ"],
    price: 60,
    shape: "Bud",
  },
  "JBL Live 300TWS": {
    features: ["Transparency mode", "In-app EQ"],
    price: 55,
    shape: "Bud",
  },
  "Powerbeats Pro": {
    features: [
      "Transparency mode",
      "Dolby Atmos",
      "In-app EQ",
      "Wear detection (auto play/pause)",
    ],
    price: 200,
    shape: "Hook",
  },
  "Xiaomi Buds 4 Pro": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Wireless charging",
      "Multipoint",
      "Spatial audio",
    ],
    price: 139,
    shape: "Stem",
  },
  "1MORE ColorBuds 2": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Wireless charging",
      "Mono mode",
      "In-ear detection",
    ],
    price: 60,
    shape: "Bud",
  },
  "Status Between 3ANC": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Wireless charging",
      "In-app EQ",
      "Multipoint",
      "Mono mode",
    ],
    price: 200,
    shape: "Stem",
  },
  "Realme Buds Air Pro": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Wear Detection",
    ],
    price: 61,
    shape: "Stem",
  },
  "Technics EAH-AZ60": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Multipoint",
      "In-app EQ",
      "Find my earbuds",
    ],
    price: 230,
    shape: "Bud",
  },
  "Audio Technica ATH-TWX7": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Multipoint",
      "In-app EQ",
    ],
    price: 199,
    shape: "Stem",
  },
  "1MORE PistonBuds Pro": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Mono mode",
      "wear detection",
    ],
    price: 60,
    shape: "Bud",
  },
  "Fairphone True Wireless Stereo Earbuds": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "In-ear detection",
      "mono mode",
    ],
    price: 109,
    shape: "Stem",
  },
  "EarFun Air Pro SV": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "In-app EQ",
      "Wireless charging",
    ],
    price: 90,
    shape: "Stem",
  },
  "OnePlus Nord Buds 2": {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "In-app EQ",
      "Dolby Atmos",
    ],
    price: 59,
    shape: "Stem",
  },
  "SOUNDPEATS Capsule3 Pro": {
    features: ["Transparency mode", "Active noise cancelling", "In-app EQ"],
    price: 59,
    shape: "Stem",
  },
  "MOMENTUM True Wireless 2": {
    features: ["Transparency mode", "Active noise cancelling", "In-app EQ"],
    price: 200,
    shape: "Bud",
  },
  "Soundcore Sport X10": {
    features: ["Transparency mode", "Active noise cancelling", "In-app EQ"],
    price: 70,
    shape: "Hook",
  },
  NuraTrue: {
    features: [
      "Transparency mode",
      "Active noise cancelling",
      "Customizable controls",
    ],
    price: 200,
    shape: "Bud",
  },
  "Skullcandy Push Active": {
    features: ["Tile tracking", "Transparency mode", "Spotify Tap"],
    price: 60,
    shape: "Hook",
  },
  "Skullcandy Grind": {
    features: ["Tile tracking", "Transparency mode"],
    price: 50,
    shape: "Bud",
  },
  "Skullcandy Dime 2": {
    features: ["Tile tracking", "Mono mode"],
    price: 20,
    shape: "Stem",
  },
  "vivo TWS 3e": {
    features: [
      "Spatial Audio",
      "Active noise cancelling",
      "Transparency mode",
      "Multipoint",
    ],
    price: 25,
    shape: "Stem",
  },
  "Sony INZONE Buds": {
    features: ["Spatial Audio", "Active noise cancelling", "2.4 GHz adapter"],
    price: 200,
    shape: "Stem",
  },
  "JLab Epic Lab Edition": {
    features: [
      "Spatial Audio",
      "wear detection",
      "Google Fast Pair",
      "Dolby Atmos",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Multipoint",
    ],
    price: 200,
    shape: "Bud",
  },
  "OnePlus Buds Pro 2 Lite": {
    features: [
      "Spatial audio",
      "Google Fast Pair",
      "Active noise cancelling",
      "Transparency mode",
    ],
    price: 115,
    shape: "Stem",
  },
  "JBL Quantum TWS": {
    features: [
      "simultaneous Bluetooth/2.4GHz connection",
      "In-app EQ",
      "Active noise cancelling",
      "2.4 GHz adapter",
      "Transparency mode",
    ],
    price: 130,
    shape: "Stem",
  },
  "Baseus Bowie MA10 TWS": {
    features: ["Quick Charge", "Active noise cancelling", "Multipoint"],
    price: 40,
    shape: "Bud",
  },
  "Soundcore VR P10": {
    features: ["Passthrough charging on dongle", "2.4 GHz adapter"],
    price: 80,
    shape: "Stem",
  },
  "OnePlus Nord Buds 2R": {
    features: ["OnePlus Fast Pair", "Dolby Atmos", "In-app EQ"],
    price: 27,
    shape: "Stem",
  },
  "1MORE Evo": {
    features: [
      "Multipoint",
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
    ],
    price: 150,
    shape: "Bud",
  },
  "EarFun Air Pro 3": {
    features: [
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Active noise cancelling",
      "Ultra Low Latency Mode",
    ],
    price: 56,
    shape: "Stem",
  },
  "Moondrop Sparks": {
    features: ["Multipoint", "NFC pairing", "mono mode"],
    price: 76,
    shape: "Bud",
  },
  "JBL Live Pro 2": {
    features: [
      "Multipoint",
      "In-app EQ",
      "Transparency mode",
      "Wireless charging",
      "Active noise cancelling",
    ],
    price: 100,
    shape: "Stem",
  },
  "FIIL CC nano": {
    features: ["Multipoint", "In-app EQ", "Low latency mode"],
    price: 70,
    shape: "Stem",
  },
  "Philips Fidelio T1": {
    features: [
      "Multipoint",
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Google Fast Pair",
      "wear detection",
    ],
    price: 109,
    shape: "Bud",
  },
  "Soundpeats Engine4": {
    features: ["Multipoint", "In-app EQ"],
    price: 59,
    shape: "Bud",
  },
  "LG TONE Free T60": {
    features: [
      "Multipoint",
      "Dolby Atmos",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "germicidal UV",
    ],
    price: 150,
    shape: "Stem",
  },
  "Jabra Elite 7 Active": {
    features: [
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Mono mode",
      "Alexa Built-in",
    ],
    price: 180,
    shape: "Bud",
  },
  "Philips T8506": {
    features: [
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Google Fast Pair",
      "wear detection",
    ],
    price: 100,
    shape: "Bud",
  },
  "Jabra Elite 5": {
    features: [
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Google Fast Pair",
      "Microsoft Swift Pair",
    ],
    price: 150,
    shape: "Bud",
  },
  "Huawei FreeBuds 5i": {
    features: [
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "Low-latency mode",
      "Find my earbuds",
      "In-ear detection",
    ],
    price: 108,
    shape: "Stem",
  },
  "Jabra Elite 4": {
    features: [
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Google Fast Pair",
      "Microsoft Swift Pair",
      "mono mode",
    ],
    price: 100,
    shape: "Bud",
  },
  "1MORE Fit Open Earbuds S50": {
    features: ["mono mode", "Wireless charging", "In-app EQ"],
    price: 150,
    shape: "Hook",
  },
  "Skullcandy Sesh Evo": {
    features: ["Mono mode", "Tile tracking"],
    price: 60,
    shape: "Bud",
  },
  "FIIL T1 XS": {
    features: ["Low-latency mode", "In-app EQ", "Transparency mode"],
    price: 45,
    shape: "Bud",
  },
  "Huawei FreeBuds Pro 3": {
    features: [
      "In-ear detection",
      "Active noise cancelling",
      "Transparency mode",
      "Multipoint",
      "Wireless charging",
      "In-app EQ",
    ],
    price: 200,
    shape: "Stem",
  },
  "PistonBuds Pro Q30": {
    features: [
      "in-ear detection",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Multipoint",
    ],
    price: 50,
    shape: "Stem",
  },
  "Edifier NB2 Pro": {
    features: [
      "In-ear detection",
      "Active noise cancelling",
      "Transparency mode",
    ],
    price: 150,
    shape: "Stem",
  },
  "Nothing Ear (2)": {
    features: [
      "In-ear detection",
      "Google Fast Pair",
      "Microsoft Swift Pair",
      "Find my earbuds",
      "Transparency mode",
      "Active noise cancelling",
      "In-app EQ",
      "Wireless charging",
      "Multipoint",
    ],
    price: 149,
    shape: "Stem",
  },
  "Jabra Elite 10": {
    features: [
      "In-ear detection",
      "Fast Pair",
      "Swift Pair",
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "Wireless charging",
      "Multipoint",
    ],
    price: 250,
    shape: "Bud",
  },
  "Jabra Elite 8 Active": {
    features: [
      "In-ear detection",
      "Fast Pair",
      "Swift Pair",
      "MIL-STD-810h",
      "Dolby Atmos",
      "Active noise cancelling",
      "Transparency mode",
      "Multipoint",
      "In-app EQ",
    ],
    price: 200,
    shape: "Bud",
  },
  "EarFun Free 2S": {
    features: ["In-app EQ", "Wireless charging"],
    price: 80,
    shape: "Bud",
  },
  "Avantree Ace M10 / Ace 130T": {
    features: ["In-app EQ", "USB bluetooth adapter", "mono mode"],
    price: 60,
    shape: "Bud",
  },
  "Klipsch T5 II True Wireless": {
    features: ["In-app EQ", "Transparency mode", "Metal case"],
    price: 150,
    shape: "Bud",
  },
  "Jabra Elite 3": {
    features: ["In-app EQ", "Transparency mode", "Alexa built-in", "mono mode"],
    price: 80,
    shape: "Bud",
  },
  "Jabra Elite 85t": {
    features: [
      "In-app EQ",
      "Transparency mode",
      "Active noise cancelling",
      "Multipoint",
      "Wireless charging",
    ],
    price: 230,
    shape: "Bud",
  },
  "Klipsch T5 II True Wireless ANC": {
    features: [
      "In-app EQ",
      "Transparency mode",
      "Active noise cancelling",
      "Metal case",
      "Dirac HD",
    ],
    price: 200,
    shape: "Bud",
  },
  "Sony WF-1000XM3": {
    features: [
      "In-app EQ",
      "Transparency mode",
      "Active noise cancelling",
      "Dolby Atmos",
    ],
    price: 200,
    shape: "Bud",
  },
  "1MORE ComfoBuds Pro": {
    features: [
      "In-app EQ",
      "Transparency mode",
      "Active noise cancelling",
      "Auto play-pause",
    ],
    price: 55,
    shape: "Stem",
  },
  "JBL Tune 130NC": {
    features: ["In-app EQ", "Transparency mode", "Active noise cancelling"],
    price: 90,
    shape: "Bud",
  },
  "Sennheiser SPORT True Wireless": {
    features: ["In-app EQ", "Transparency mode"],
    price: 100,
    shape: "Bud",
  },
  "JLab Air Sport 3rd gen": {
    features: [
      "In-app EQ",
      "Tile tracking",
      "Multipoint",
      "Transparency mode",
      "Mono mode",
      "Google Fast Pair",
    ],
    price: 70,
    shape: "Hook",
  },
  "JLab JBuds Air Pro": {
    features: [
      "In-app EQ",
      "Tile tracking",
      "Multipoint",
      "Transparency mode",
      "Mono mode",
    ],
    price: 60,
    shape: "Bud",
  },
  "JLab Epic Air Sport ANC 2nd gen": {
    features: [
      "In-app EQ",
      "Tile tracking",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Low-latency mode",
      "wear detection",
      "Google Fast Pair",
    ],
    price: 80,
    shape: "Hook",
  },
  "Sony WF-1000XM4": {
    features: [
      "In-app EQ",
      "Multipoint",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 280,
    shape: "Bud",
  },
  "Jabra Elite 65t": {
    features: ["In-app EQ", "Multipoint"],
    price: 70,
    shape: "Bud",
  },
  "Jaybird Vista": {
    features: ["In-app EQ", "mono mode", "find my buds"],
    price: 150,
    shape: "Bud",
  },
  "QCY T6": {
    features: ["In-app EQ", "Mono mode"],
    price: 25,
    shape: "Hook",
  },
  "FIIL T1 Lite": {
    features: ["In-app EQ", "Low-latency mode", "mono mode"],
    price: 45,
    shape: "Bud",
  },
  "Sony WF-C500": {
    features: ["In-app EQ", "Google Fast Pair", "Microsoft Swift Pair"],
    price: 70,
    shape: "Bud",
  },
  "Realme Buds Air 3S": {
    features: ["In-app EQ", "Dolby Atmos"],
    price: 28,
    shape: "Stem",
  },
  "Sennheiser CX True Wireless": {
    features: ["In-app EQ", "Customizable touch controls"],
    price: 80,
    shape: "Bud",
  },
  "LG TONE Free FP8": {
    features: [
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "UV disinfecting case",
      "Fast Pair",
      "Swift Pair",
    ],
    price: 180,
    shape: "Stem",
  },
  "Beyerdynamic Free Byrd": {
    features: [
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 230,
    shape: "Bud",
  },
  "FIIL CC Pro2": {
    features: [
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Sleep mode",
      "wear detection",
    ],
    price: 100,
    shape: "Stem",
  },
  "Surface Earbuds": {
    features: [
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Mono mode",
    ],
    price: 200,
    shape: "Bud",
  },
  "Soundcore Life A3i": {
    features: [
      "In-app EQ",
      "Active noise cancelling",
      "Transparency mode",
      "Mono mode",
    ],
    price: 60,
    shape: "Bud",
  },
  "Edifier NeoBuds Pro": {
    features: ["In-app EQ", "Active noise cancelling", "Transparency mode"],
    price: 100,
    shape: "Stem",
  },
  "HyperX Cloud MIX Buds": {
    features: ["In-app EQ", "2.4 GHz adapter", "In-ear detection"],
    price: 120,
    shape: "Stem",
  },
  "Bose QuietComfort Ultra Earbuds": {
    features: [
      "Google Fast Pair",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Dolby Atmos",
    ],
    price: 300,
    shape: "Stem",
  },
  "Soundcore Liberty 4 NC": {
    features: [
      "Google Fast Pair",
      "wear detection",
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Multipoint",
    ],
    price: 100,
    shape: "Stem",
  },
  "realme Buds Air 5 Pro": {
    features: [
      "Google Fast Pair",
      "spatial audio",
      "Active noise cancelling",
      "Transparency mode",
    ],
    price: 60,
    shape: "Stem",
  },
  "AirPods Pro (2nd generation, Lightning)": {
    features: [
      "Ear detection",
      "Wireless charging",
      "Transparency mode",
      "Active noise cancelling",
      "Dolby Atmos",
      "In-app EQ",
    ],
    price: 250,
    shape: "Stem",
  },
  "AirPods Pro (2nd generation, USB-C)": {
    features: [
      "Ear detection",
      "Lossless Audio with Vision Pro",
      "Wireless charging",
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "In-app EQ",
    ],
    price: 250,
    shape: "Stem",
  },
  "OnePlus Nord Buds": {
    features: ["Dolby Atmos", "In-app EQ"],
    price: 40,
    shape: "Stem",
  },
  "Denon PerL Pro": {
    features: [
      "Dirac Virtuo",
      "wear detection",
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "In-app EQ",
      "Multipoint",
    ],
    price: 349,
    shape: "Bud",
  },
  "Soundcore A20i": {
    features: ["detachable lanyard", "mono mode"],
    price: 30,
    shape: "Bud",
  },
  "Razer Hammerhead Hyperspeed": {
    features: [
      "Chroma RGB",
      "simultaneous USB/bluetooth connection",
      "Active noise cancelling",
      "2.4 GHz adapter",
      "Wireless charging",
      "In-app EQ",
      "Transparency mode",
    ],
    price: 150,
    shape: "Stem",
  },
  "Philips Fidelio T2": {
    features: [
      "Auracast",
      "wear detection",
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Multipoint",
      "Wireless charging",
    ],
    price: 279,
    shape: "Bud",
  },
  "Sennheiser Momentum True Wireless 4": {
    features: [
      "Auracast",
      "LE Audio",
      "Active noise cancelling",
      "In-app EQ",
      "Transparency mode",
      "Wireless charging",
      "Multipoint",
    ],
    price: 300,
    shape: "Bud",
  },
  "Beats Studio Buds +": {
    features: [
      "Apple Find My",
      "Google Fast Pair",
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "Multipoint",
    ],
    price: 170,
    shape: "Bud",
  },
  "Soundcore Liberty 4": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
      "Multipoint",
      "In-app EQ",
      "Heart rate monitor",
    ],
    price: 150,
    shape: "Stem",
  },
  "OnePlus Buds Pro 2": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
      "Multipoint",
    ],
    price: 130,
    shape: "Stem",
  },
  "Creative Outlier Air V3": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
      "mono mode",
    ],
    price: 42,
    shape: "Bud",
  },
  "FIIL CC Pro": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
    ],
    price: 53,
    shape: "Stem",
  },
  "Galaxy Buds2": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
      "In-app EQ",
    ],
    price: 90,
    shape: "Bud",
  },
  "Bowers & Wilkins Pi7 S2": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
      "Audio retransmission",
      "wear detection",
    ],
    price: 400,
    shape: "Bud",
  },
  "1MORE ComfoBuds Mini": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Transparency mode",
    ],
    price: 80,
    shape: "Bud",
  },
  "1MORE Aero": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "Multipoint",
      "Transparency mode",
      "In-app EQ",
      "Spatial Audio",
    ],
    price: 110,
    shape: "Stem",
  },
  "1MORE ColorBuds": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "In-ear detection",
    ],
    price: 60,
    shape: "Bud",
  },
  "Nothing Ear (1)": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "In-app EQ",
      "Transparency mode",
      "In-ear detection",
    ],
    price: 100,
    shape: "Stem",
  },
  "Beoplay EX": {
    features: [
      "Active noise cancelling",
      "Wireless charging",
      "In-app EQ",
      "Multipoint",
      "Transparency mode",
      "Google Fast Pair",
      "Microsoft Swift Pair",
    ],
    price: 400,
    shape: "Stem",
  },
  "Omthing (1MORE) Airfree 2": {
    features: ["Active noise cancelling", "Wireless charging"],
    price: 40,
    shape: "Stem",
  },
  "Xiaomi Buds 3T Pro": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Multipoint",
      "Spatial audio",
    ],
    price: 150,
    shape: "Stem",
  },
  "Master & Dynamic MW08 Sport": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Multipoint",
      "IPX4 case",
      "USB-A bluetooth adapter",
    ],
    price: 349,
    shape: "Bud",
  },
  "Xiaomi Buds 3": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Multipoint",
    ],
    price: 93,
    shape: "Stem",
  },
  "Xiaomi Buds 3 Pro": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Multipoint",
    ],
    price: 93,
    shape: "Stem",
  },
  "Belkin SoundForm Flow": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "Mono mode",
    ],
    price: 90,
    shape: "Stem",
  },
  "EarFun Air S": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Multipoint",
    ],
    price: 70,
    shape: "Stem",
  },
  "Echo Buds (2nd Gen)": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Alexa built-in",
    ],
    price: 100,
    shape: "Bud",
  },
  "Baseus Bowie M2 Plus": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 40,
    shape: "Stem",
  },
  "Earfun Air Pro 2": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 60,
    shape: "Stem",
  },
  "Earfun Free Pro 2": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 60,
    shape: "Bud",
  },
  "Beoplay EQ": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Multipoint",
      "Wireless charging",
      "In-app EQ",
      "In-ear detection",
    ],
    price: 300,
    shape: "Bud",
  },
  "Redmi Buds 4 Pro": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Multipoint",
      "In-ear detection",
    ],
    price: 100,
    shape: "Stem",
  },
  "vivo TWS 3": {
    features: ["Active noise cancelling", "Transparency mode", "Multipoint"],
    price: 70,
    shape: "Stem",
  },
  "EarFun Air Pro": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Mono mode",
      "in-ear detection",
    ],
    price: 80,
    shape: "Stem",
  },
  "Redmi Buds 4": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Low-latency mode",
      "in-ear detection",
    ],
    price: 29,
    shape: "Bud",
  },
  "SOUNDPEATS Mini Pro HS": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Low-latency mode",
    ],
    price: 60,
    shape: "Bud",
  },
  "Logitech Zone True Wireless": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Multipoint",
      "USB-A Bluetooth receiver",
    ],
    price: 300,
    shape: "Bud",
  },
  "Soundcore Space A40": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Multipoint",
    ],
    price: 100,
    shape: "Bud",
  },
  "Lypertek PurePlay Z5": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Wireless charging",
      "Find my earbuds",
    ],
    price: 99,
    shape: "Stem",
  },
  "Sony LinkBuds S": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Multipoint",
    ],
    price: 200,
    shape: "Bud",
  },
  "Audio-Technica ATH-TWX9": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "In-app EQ",
      "Multipoint",
    ],
    price: 300,
    shape: "Stem",
  },
  "Asus ROG Cetera True Wireless": {
    features: ["Active noise cancelling", "Transparency mode", "In-app EQ"],
    price: 80,
    shape: "Stem",
  },
  "Edifier NeoBuds S": {
    features: ["Active noise cancelling", "Transparency mode", "In-app EQ"],
    price: 180,
    shape: "Stem",
  },
  "Bose QuietComfort Earbuds II": {
    features: ["Active noise cancelling", "Transparency mode", "In-app EQ"],
    price: 300,
    shape: "Stem",
  },
  "Edifier W240TN": {
    features: ["Active noise cancelling", "Transparency mode", "In-app EQ"],
    price: 80,
    shape: "Bud",
  },
  "Jabra Elite 4 Active": {
    features: ["Active noise cancelling", "Transparency mode", "In-app EQ"],
    price: 80,
    shape: "Bud",
  },
  "TCL MOVEAUDIO Neo": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Google Fast Pair",
    ],
    price: 50,
    shape: "Stem",
  },
  "Galaxy Buds Pro": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "Wireless charging",
      "Automatic transparency",
    ],
    price: 180,
    shape: "Bud",
  },
  "Beats Fit Pro": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "In-ear detection",
    ],
    price: 200,
    shape: "Bud",
  },
  "OnePlus Buds Z2": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Dolby Atmos",
      "In-app EQ",
      "Mono mode (via app)",
    ],
    price: 80,
    shape: "Stem",
  },
  "SOUNDPEATS T3": {
    features: [
      "Active noise cancelling",
      "Transparency mode",
      "Battery indicator",
    ],
    price: 56,
    shape: "Stem",
  },
  "Moondrop Space Travel": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 25,
    shape: "Stem",
  },
  "SOUNDPEATS Life": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 50,
    shape: "Stem",
  },
  "OPPO Enco Free3": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 73,
    shape: "Stem",
  },
  "OPPO Enco Free2": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 83,
    shape: "Stem",
  },
  "SOUNDPEATS Air3 Pro": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 80,
    shape: "Stem",
  },
  "Mpow X3 (version 2)": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 70,
    shape: "Stem",
  },
  "SOUNDPEATS Mini Pro": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 70,
    shape: "Bud",
  },
  "NuraBuds 2": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 120,
    shape: "Bud",
  },
  "AKG N400NC TWS": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 150,
    shape: "Bud",
  },
  NuraBuds: {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 140,
    shape: "Bud",
  },
  "SOUNDPEATS T2": {
    features: ["Active noise cancelling", "Transparency mode"],
    price: 70,
    shape: "Bud",
  },
  "Jabra Elite 7 Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
      "In-app EQ",
      "Alexa Built-in",
    ],
    price: 200,
    shape: "Bud",
  },
  "vivo TWS 3 Pro": {
    features: [
      "Active noise cancelling",
      "Multipoint",
      "Transparency mode",
      "Body temperature sensor",
    ],
    price: 140,
    shape: "Stem",
  },
  "Moondrop Nekocake (2021)": {
    features: ["Active noise cancelling", "Mono mode"],
    price: 43,
    shape: "Stem",
  },
  "JLab Epic Air Sport ANC": {
    features: [
      "Active noise cancelling",
      "In-app EQ",
      "Transparency mode",
      "Tile tracking",
      "Wireless charging",
      "Wear detection",
    ],
    price: 80,
    shape: "Hook",
  },
  "Razer Hammerhead True Wireless Pro": {
    features: [
      "Active noise cancelling",
      "In-app EQ",
      "Transparency mode",
      "THX Certified",
      "Low-latency mode",
    ],
    price: 100,
    shape: "Stem",
  },
  "Beats Studio Buds": {
    features: [
      "Active noise cancelling",
      "In-app EQ",
      "Transparency mode",
      "Dolby Atmos",
    ],
    price: 100,
    shape: "Bud",
  },
  "Razer Hammerhead True Wireless (2021)": {
    features: [
      "Active noise cancelling",
      "In-app EQ",
      "Transparency mode",
      "Chroma RGB",
    ],
    price: 90,
    shape: "Stem",
  },
  "JBL Tune 230NC": {
    features: ["Active noise cancelling", "In-app EQ", "Transparency mode"],
    price: 70,
    shape: "Stem",
  },
  "Pixel Buds Pro": {
    features: [
      "Active noise cancelling",
      "In-app EQ",
      "Multipoint",
      "Transparency mode",
      "Wireless charging",
    ],
    price: 200,
    shape: "Bud",
  },
  "Logitech G FITS": {
    features: ["2.4 GHz adapter", "In-app EQ"],
    price: 180,
    shape: "Stem",
  },
  "AirPods (3rd generation)": {
    features: [
      "Wireless charging",
      "In-app EQ",
      "Spatial Audio",
      "wear detection",
      "Magsafe",
    ],
    price: 180,
    shape: "Stem",
  },
  "Marshall Minor III": {
    features: ["Wireless charging", "In-app EQ", "Mono mode"],
    price: 130,
    shape: "Stem",
  },
  "Soundpeats Air4 Lite": {
    features: ["Multipoint", "In-app EQ"],
    price: 40,
    shape: "Stem",
  },
  "Nothing Ear (stick)": {
    features: ["Multipoint", "In-app EQ"],
    price: 100,
    shape: "Stem",
  },
  "Sony LinkBuds": {
    features: ["Multipoint", "In-app EQ"],
    price: 180,
    shape: "Bud",
  },
  "SoundPEATS Air4": {
    features: ["Multipoint", "Active noise cancelling"],
    price: 90,
    shape: "Stem",
  },
  "Tranya F4": {
    features: ["Low-latency mode", "mono mode"],
    price: 60,
    shape: "Stem",
  },
  "Huawei FreeBuds 5": {
    features: ["In-app EQ", "Wireless charging", "Active noise cancelling"],
    price: 131,
    shape: "Stem",
  },
  "Soundcore Life Note 3S": {
    features: ["In-app EQ", "low-latency/gaming mode"],
    price: 70,
    shape: "Stem",
  },
  "FIIL Key": {
    features: ["In-app EQ", "Low-latency mode"],
    price: 48,
    shape: "Stem",
  },
  "Echo Buds (2023)": {
    features: ["Alexa built-in", "Find My Echo Buds", "Multipoint"],
    price: 50,
    shape: "Stem",
  },
  "Galaxy Buds Live": {
    features: ["Active noise cancelling", "Wireless charging", "In-app EQ"],
    price: 80,
    shape: "Bud",
  },
  "Xiaomi Buds 4": {
    features: ["Active noise cancelling", "Transparency mode", "Spatial audio"],
    price: 102,
    shape: "Stem",
  },
  "vivo TWS Air Pro": {
    features: ["3D audio", "Active noise cancelling"],
    price: 42,
    shape: "Stem",
  },
};
export default knowledgeBase;
