export const Unique_Shapes_of_Earbuds = ["Bud", "Stem", "Hook"];
export const Price_Range_of_Earbuds = [20.0, 405.0];

export const Set_Of_features = [
  "Active noise cancelling",
  "In-app eq",
  "Transparency mode",
  "Wear detection",
  "Wireless charging",
  "24-bit",
  "Fast pair",
  "Multipoint",
  "Dolby atmos",
  "Dolby head tracking",
  "Audio retransmission",
  "In-ear detection",
  "Tile tracking",
  "Spatial audio",
  "Battery percentage meter",
  "Mono mode",
  "Thx certified",
  "Warp charge",
  "Mil-std-810g",
  "User-replaceable batteries",
  "Apple find my",
  "Find my earbuds",
  "Google fast pair",
  "Battery level indicator",
  "Low-latency mode",
  "Dsee",
  "Microsoft swift pair",
  "Wear detection (auto play/pause)",
  "2.4 ghz adapter",
  "Simultaneous bluetooth/2.4ghz connection",
  "Ultra low latency mode",
  "Germicidal uv",
  "Alexa built-in",
  "Swift pair",
  "Mil-std-810h",
  "Dirac hd",
  "Metal case",
  "Auto play-pause",
  "Uv disinfecting case",
  "Sleep mode",
  "Ear detection",
  "Lossless audio with vision pro",
  "Dirac virtuo",
  "Chroma rgb",
  "Simultaneous usb/bluetooth connection",
  "Auracast",
  "Le audio",
  "Heart rate monitor",
  "Ipx4 case",
  "Usb-a bluetooth adapter",
  "Usb-a bluetooth receiver",
  "Automatic transparency",
  "Mono mode (via app)",
  "Body temperature sensor",
  "Magsafe",
  "3d audio",
];

export const earbud_categories = [
  {
    categoria: "Modes",
    opciones: [
      "Mono mode",
      "Mono mode (via app)",
      "Transparency mode",
      "Low-latency mode",
      "Ultra low latency mode",
      "Spatial audio",
      "3d audio",
      "Automatic transparency",
    ],
  },
  {
    categoria: "Detection",
    opciones: [
      "Wear detection",
      "Wear detection (auto play/pause)",
      "In-ear detection",
      "Ear detection",
      "Auto play-pause",
    ],
  },
  {
    categoria: "Audio Enhancements",
    opciones: [
      "Active noise cancelling",
      "Dolby atmos",
      "Dolby head tracking",
      "24-bit",
      "Thx certified",
      "Dsee",
      "Dirac hd",
      "Dirac virtuo",
      "Lossless audio with vision pro",
    ],
  },
  {
    categoria: "Connectivity",
    opciones: [
      "Fast pair",
      "Google fast pair",
      "Microsoft swift pair",
      "Swift pair",
      "2.4 ghz adapter",
      "Usb-a bluetooth adapter",
      "Usb-a bluetooth receiver",
      "Simultaneous bluetooth/2.4ghz connection",
      "Simultaneous usb/bluetooth connection",
      "Alexa built-in",
      "Auracast",
      "Le audio",
    ],
  },
  {
    categoria: "Charging",
    opciones: ["Wireless charging", "Warp charge"],
  },
  {
    categoria: "Tracking",
    opciones: [
      "Tile tracking",
      "Apple find my",
      "Find my earbuds",
      "Battery level indicator",
      "Battery percentage meter",
    ],
  },
  {
    categoria: "Environmental Resistance",
    opciones: ["Mil-std-810g", "Mil-std-810h", "Ipx4 case"],
  },
  {
    categoria: "User Customization",
    opciones: ["In-app eq", "Chroma rgb"],
  },
  {
    categoria: "Health Monitoring",
    opciones: ["Heart rate monitor", "Body temperature sensor"],
  },
  {
    categoria: "Case Features",
    opciones: [
      "Metal case",
      "Uv disinfecting case",
      "Germicidal uv",
      "Magsafe",
    ],
  },
  {
    categoria: "Other",
    opciones: [
      "Audio retransmission",
      "Sleep mode",
      "User-replaceable batteries",
    ],
  },
];
