export const Unique_Shapes_of_Earbuds = ["Bud", "Stem", "Hook"];
export const Price_Range_of_Earbuds = [20.0, 405.0];

export const Set_Of_features = [
  "Wireless charging",
  "Wear detection. mono mode",
  "Transparency mode",
  "In-app EQ",
  "Active noise cancelling",
  "Wear detection",
  "Multipoint",
  "Fast Pair",
  "24-bit",
  "Dolby Atmos",
  "Dolby Head Tracking",
  "audio retransmission",
  "in-ear detection",
  "Tile tracking",
  "spatial Audio",
  "Mono mode",
  "In-ear detection",
  "Battery percentage meter",
  "THX Certified",
  "wear detection",
  "Warp charge",
  "MIL-STD-810G",
  "User-replaceable batteries",
  "Apple Find My",
  "Find my earbuds",
  "Google Fast Pair",
  "Battery level indicator",
  "low-latency mode",
  "DSEE",
  "Microsoft Swift Pair",
  "Wear detection (auto play/pause)",
  "Spatial audio",
  "Wear Detection",
  "mono mode",
  "Customizable controls",
  "Spotify Tap",
  "Spatial Audio",
  "2.4 GHz adapter",
  "simultaneous Bluetooth/2.4GHz connection",
  "Quick Charge",
  "Passthrough charging on dongle",
  "OnePlus Fast Pair",
  "Ultra Low Latency Mode",
  "NFC pairing",
  "Low latency mode",
  "germicidal UV",
  "Alexa Built-in",
  "Low-latency mode",
  "Swift Pair",
  "MIL-STD-810h",
  "USB bluetooth adapter",
  "Metal case",
  "Alexa built-in",
  "Dirac HD",
  "Auto play-pause",
  "find my buds",
  "Customizable touch controls",
  "UV disinfecting case",
  "Sleep mode",
  "spatial audio",
  "Ear detection",
  "Lossless Audio with Vision Pro",
  "Dirac Virtuo",
  "detachable lanyard",
  "Chroma RGB",
  "simultaneous USB/bluetooth connection",
  "Auracast",
  "LE Audio",
  "Heart rate monitor",
  "Audio retransmission",
  "IPX4 case",
  "USB-A bluetooth adapter",
  "USB-A Bluetooth receiver",
  "Automatic transparency",
  "Mono mode (via app)",
  "Battery indicator",
  "Body temperature sensor",
  "Magsafe",
  "low-latency/gaming mode",
  "Find My Echo Buds",
  "3D audio",
];

export const earbud_categories = [
  {
    categoria: "Modes",
    opciones: [
      "Mono mode",
      "Transparency mode",
      "low-latency mode",
      "Low-latency mode",
      "Ultra Low Latency Mode",
      "low-latency/gaming mode",
      "Spatial audio",
      "spatial Audio",
      "Spatial Audio",
      "3D audio",
    ],
  },
  {
    categoria: "Detection",
    opciones: [
      "Wear detection",
      "Wear detection (auto play/pause)",
      "Wear Detection",
      "Wear detection. mono mode",
      "in-ear detection",
      "In-ear detection",
      "Ear detection",
      "Auto play-pause",
    ],
  },
  {
    categoria: "Audio Enhancements",
    opciones: [
      "Active noise cancelling",
      "Dolby Atmos",
      "Dolby Head Tracking",
      "24-bit",
      "THX Certified",
      "DSEE",
      "Dirac HD",
      "Dirac Virtuo",
      "Lossless Audio with Vision Pro",
    ],
  },
  {
    categoria: "Connectivity",
    opciones: [
      "Multipoint",
      "Fast Pair",
      "Google Fast Pair",
      "Microsoft Swift Pair",
      "OnePlus Fast Pair",
      "Swift Pair",
      "NFC pairing",
      "2.4 GHz adapter",
      "USB bluetooth adapter",
      "USB-A bluetooth adapter",
      "USB-A Bluetooth receiver",
      "simultaneous Bluetooth/2.4GHz connection",
      "simultaneous USB/bluetooth connection",
      "Alexa Built-in",
      "Alexa built-in",
      "Auracast",
      "LE Audio",
    ],
  },
  {
    categoria: "Charging",
    opciones: [
      "Wireless charging",
      "Warp charge",
      "Quick Charge",
      "Passthrough charging on dongle",
    ],
  },
  {
    categoria: "Tracking",
    opciones: [
      "Tile tracking",
      "Apple Find My",
      "Find my earbuds",
      "find my buds",
      "Battery level indicator",
      "Battery percentage meter",
      "Battery indicator",
      "Find My Echo Buds",
    ],
  },
  {
    categoria: "Environmental Resistance",
    opciones: ["MIL-STD-810G", "MIL-STD-810h", "IPX4 case"],
  },
  {
    categoria: "User Customization",
    opciones: [
      "In-app EQ",
      "Customizable controls",
      "Customizable touch controls",
      "Chroma RGB",
    ],
  },
  {
    categoria: "Health Monitoring",
    opciones: ["Heart rate monitor", "Body temperature sensor"],
  },
  {
    categoria: "Case Features",
    opciones: [
      "Metal case",
      "UV disinfecting case",
      "detachable lanyard",
      "Magsafe",
      "germicidal UV",
    ],
  },
  {
    categoria: "Other",
    opciones: ["audio retransmission", "Audio retransmission", "Sleep mode"],
  },
];
